// This file is generated by Casasoft Contemporary Carte de Visite Tools
// https://github.com/strawberryfield/Contemporary_CDV

using CCDV_App1;
using ImageMagick;

#region texts
string desc = "Brief description of the program";
string longDesc = @"The long description 
of the program.";
#endregion

#region command line
CommandLineClass par = new("outfilename", desc)
{
    Usage = "[options]* inputfile+",
    LongDesc = longDesc
};
if (par.Parse(args)) return;

par.ExpandWildcards();
#endregion

EngineClass engine = new(par);
MagickImage final = engine.GetResult();
engine.fmt.SetImageParameters(final, par.Extension);
final.Write($"{par.OutputName}.{par.Extension}");
