// This file is generated by Casasoft Contemporary Carte de Visite Tools
// https://github.com/strawberryfield/Contemporary_CDV

using Casasoft.CCDV.Scripting;

namespace CCDV_App1;

internal class ScriptingClass : BaseScripting
{
}
